---
driver:
  name: vagrant

  network:
  - ["forwarded_port", {guest: 80, host: 8080}]

  customize:
    memory: 2048

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.6.0

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - "recipe[rails-cluster::default]"
    attributes: { gitrepo: "https://github.com/knifecluster/rails-cluster" }
