# Encoding: utf-8
name             'rails-cluster'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'none'
license          ''
description      'Installs/Configures rails-stack'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'rbenv'
depends          'apt'
depends          'application'
depends          'application_ruby'
depends          'passenger_apache2'
depends          'apache2'
depends          'git'
depends          'nodejs'
depends          'rackspace_user'
